// src/components/api/endPoints.ts

const endPoints = {
  // Existing ones...
  login: "/auth/login",
  register: "/auth/register",
  applicantsRegister:
    "https://deutschemedizin-collage-backend-production.up.railway.app/api/applicants/register",
  registrarApplicantRegister: "/auth/register/student",
  studentStatus: "/student-statuses",
  studentDashboard: "/student/dashboard",
  profile: "/students/profile",
  academicYears: "/academic-years",
  gradingSystem: "/grading-systems",
  studentCopy: "/student-copy/generate",
  studentGradeReports: "/student/grade-reports",
  semesters: "/semesters",
  attritionCauses: "/attrition-causes",
  batchClassSemsterYear: "/bcsy",
  applicantsList: "/applicants",
  applicantDetail: "/applicants/:id",
  applicantUpdateStatus: "/applicants/:id/status",
  applicantPhoto: "/applicants/:id/photo",
  applicantDocument: "/applicants/:id/document",
  enrollmentTypes: "/enrollment-type",
  courseCategory: "/course-categories",
  programModality: "/program-modality",
  students: "/students",
  studentsDeactivation: "/students/:id/disable",
  studentsActivation: "/students/:id/enable",
  resetStudentPassword:
    "/auth/registrar/students/:studentUserId/reset-password",
  createDepartmentHead: "/auth/create-department-head",
  createTeacher: "/auth/create-teacher",
  departmentHeads: "/department-heads",
  teachers: "/teachers",
  departments: "/departments",
  impairments: "/impairments",
  specificImpairtment: "/impairments/:id",
  singleImpairment: "/impairments/single",
  schoolBackgrounds: "/school-backgrounds",
  classYears: "/class-years",
  BatchClassYearSemesters: "/bcsy",
  batches: "/batches",
  singleBatch: "/batches/:id",
  courses: "/courses/single",
  allCourses: "/courses",
  courseById: "/courses/:id",
  regions: "/region",
  allWoreda: "/woreda",
  allZones: "/zone",
  allRegion: "/region",
  zonesByRegion: "/zone/region",
  woredasByZone: "/woreda/zone",
  notifications: "/notifications/me",
  notificationsLatest: "/notifications/me/latest",
  markNotificationRead: "/notifications/:id/read",
  markAllNotificationsRead: "/notifications/me/read-all",
  programLevels: "/program-levels",
  programLevelByCode: "/program-levels/:id",
  programModalities: "/program-modality",
  generateGradeReport: "/grade-report/generate",
  programModalityByCode: "/program-modality/:id",
  studentsSlip: "/students/slip-production",
  lookupsDropdown: "/filters/options",
  slipPreview: "student-slips/preview",
  generateSlips: "/student-slips/generate",
  addCourse: "/student-course-scores/add",
  updateScore:
    "/student-course-scores/score/:studentId/:courseId/:batchClassYearSemesterId",
  updateReleaseStatus:
    "/student-course-scores/release/:studentId/:courseId/:batchClassYearSemesterId",
  getGrade: "/student-course-scores/:scoreId/grade",
  getAll: "/student-course-scores/all",
  bulkUpdate: "/student-course-scores/bulk-update",
  getCurrentUser: "/auth/me",
  changePassword: "/auth/me/change-password",
  getTeacherProfile: "/teachers/profile",
};

export default endPoints;
